services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoshi123
      POSTGRES_DB: sofkadb
    ports:
      - "5432:5432"
    volumes:
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
  service-a:
    build:
      context: ./SofkaMicroservicio1
      args:
        DB_PRIMARY_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
        DB_USERNAME: postgres
        DB_PASSWORD: yoshi123
        JWT_SECRET: EstaEsUnaFraseSecretaParaPoderProbar
        JWT_EXPIRATION_MINUTES: 6000000
        HASH_STRENGTH: 10
        KEY_ID: key-2025-08
        RUN_TESTS: "true"   # Cambia a "false" si quieres saltar tests
    image: myorg/service-a:local
    container_name: service-a
    env_file:
      - SofkaMicroservicio1/.env
    ports:
      - "8081:8080"
    # host:container
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  service-b:
    build:
      context: ./SofkaMicroservicio2
      args:
        DB_PRIMARY_DATASOURCE_URL: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
        DB_USERNAME: postgres
        DB_PASSWORD: yoshi123
        MS1_URL: test
        ISSUER_URI: test
        RUN_TESTS: "true"
    image: myorg/service-b:local
    container_name: service-b
    env_file:
      - SofkaMicroservicio2/.env
    environment:
      MS1_URL: http://service-a:8080
      ISSUER_URI=http://service-a:8080/.well-known/jwks.json:
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    depends_on:
      - service-a